<?php $_config_vars = array (
  'compraLocal' => 'Compra Local',
  'compraImportada' => 'Compra Importada',
  'traspasoDeSucursal' => 'Traspaso de Sucursal',
  'traspasoHaciaSucursal' => 'Traspaso a Sucursal',
  'traspasoHaciaProduccion' => 'Traspaso a Produccion',
  'productoTerminado' => 'Producto Terminado',
  'inventarioInicial' => 'Inventario Inicial',
  'venta' => 'Venta',
  'ajusteManual' => 'Ajuste Manual',
  'ajusteAutomatico' => 'Ajuste Mantenimiento',
  'ordenProduccion' => 'Orden de Produccion',
  'monedaBolivia' => 'Bolivianos',
  'monedaUsa' => 'Dolares Americanos',
); ?>